#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define MAX_NAME_LEN 20
#define MAX_PLAYERS 4
#define START_POS 1
#define MAX_SQUARES 64
#define MAX_TYPE_NAME 30

#define DIM_TAVOLA 8
#define MAX_CASELLE 64
#define MAX_SPECIALI 20

#endif // CONFIG_H_INCLUDED
